use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '9.0'

target 'ZMUIKit_Example' do
  pod 'ZMUIKit', :path => '../'

  
  
#  pod 'Masonry'
#  pod 'HBDNavigationBar' ,'1.6.0'
#  pod 'IQKeyboardManager'
#  pod 'SDWebImage', '5.4.2'
   
  target 'ZMUIKit_Tests' do
    inherit! :search_paths

    
  end
end
